name: "lg_code"
version: "1.0.0"

profile: "lg_code"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros", "shared/macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  lg_code:
    +database: lg_code
    main:
      raw:
        +materialized: table
      stg:
        +materialized: view
      mart:
        +materialized: view
